-- MySQL Script generated by MySQL Workbench
-- Tue Aug 30 10:07:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema meal_sharing
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema meal_sharing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `meal_sharing` DEFAULT CHARACTER SET utf8 ;
USE `meal_sharing` ;

-- -----------------------------------------------------
-- Table `meal_sharing`.`meal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meal_sharing`.`meal` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `description` TEXT(500) NULL,
  `location` VARCHAR(300) NULL,
  `when` DATETIME NULL,
  `max_reservations` INT UNSIGNED NULL,
  `price` DECIMAL(10,2) UNSIGNED NULL,
  `created_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meal_sharing`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meal_sharing`.`reservation` (
  `id` INT UNSIGNED NOT NULL,
  `number_of_guests` INT UNSIGNED NULL,
  `meal_id` INT UNSIGNED NULL,
  `created_date` DATE NULL,
  `contact_phone_number` VARCHAR(45) NULL,
  `contact_name` VARCHAR(200) NULL,
  `contact_email` VARCHAR(250) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reservation_meal_id_idx` (`meal_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_meal_id`
    FOREIGN KEY (`meal_id`)
    REFERENCES `meal_sharing`.`meal` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meal_sharing`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meal_sharing`.`review` (
  `id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(100) NULL,
  `description` TEXT(500) NULL,
  `meal_id` INT UNSIGNED NULL,
  `stars` INT UNSIGNED NULL,
  `created_date` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_review_meal_id_idx` (`meal_id` ASC) VISIBLE,
  CONSTRAINT `fk_review_meal_id`
    FOREIGN KEY (`meal_id`)
    REFERENCES `meal_sharing`.`meal` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
